AllCops:
  SuggestExtensions: false
  NewCops: enable
Style/MixinUsage:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']