version: '3.1'
services:
  service_a:
    container_name: serv_a
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rackup --host 0.0.0.0 --port 9292
    ports:
      - 5001:9292
    volumes:
      - .:/app
